version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test2Project
  gitServerName: sbnew
  gitUrl: https://github.com/sbudhira
  gitUsername: sbudhira
  gitBranch: main
services:
- serviceName: project.test2.integrations:fs2
  packages:
  - name: Test2Project
    version: "1.0"
- serviceName: pub.alert:channels
  packages:
  - name: WmPublic
    version: 11.1.0.0.2032
